### ISSUE TITLE
Fix ng2 tests

### ISSUE THREAD

**Issue by ericmdantas** [ericmdantas/generator-ng-fullstack#101]
Now, there's no tests being run and this is being reported:

```
Chrome 49.0.2623 (Windows 10 0.0.0): Executed 0 of 0 ERROR (0.002 secs / 0 secs)
```

**Comment by georgeedwards** [comment]
@ericmdantas This is the issue I think I am facing on my repo too. I'll look into it.

**Comment by ericmdantas** [comment]
https://github.com/ericmdantas/angular2-typescript-todo has got karma.conf.js and karma-shim-test.js configured correctly. That could help.

**Comment by ericmdantas** [comment]
Currenct stack:

```shell
C:\Users\somewhere>gulp client.unit_test
[23:50:34] Requiring external module babel-core/register
[23:50:36] Using gulpfile ~\Documents\projects\t2\gulpfile.babel.js
[23:50:36] Starting 'client.unit_test'...
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 50.0.2661 (Windows 10 0.0.0)]: Connected on socket vwZUynGeyu_yQ7d5ufR7 with id 64791783
ERROR [karma]: [TypeError: (msg || "").replace is not a function]
TypeError: (msg || "").replace is not a function
  at C:\Users\somewhere\node_modules\karma\lib\reporter.js:36:23
  at [object Object].onBrowserError (C:\Users\somewhere\node_modules\karma\lib\reporters\base.js:58:60)
  at [object Object].<anonymous> (C:\Users\somewhere\node_modules\karma\lib\events.js:14:22)
  at emitTwo (events.js:100:13)
[...]
```

Looks like there's no interaction between karma/karma-shim and the test files.

**Comment by ericmdantas** [comment]
Update it to rc1.

**Comment by vanminhnhat** [comment]
Hi,

I just install ng-fullstack yesterday.
But I facing when run nom run test-client, the error is "Failed to load todo/templates/todo.html" as the attachment.

I run in OSX.

<img width="1244" alt="unit-test-cannot-load templateurl" src="https://cloud.githubusercontent.com/assets/2121721/15631388/8b439966-2592-11e6-971f-a9a72ed74c32.png">
Is it a bug? Do we have any work around?

Thanks,

**Comment by ericmdantas** [comment]
Hello, @vanminhnhat.

Yes, its a known bug, but I'm seeing what I can do to fix it.
