### ISSUE TITLE
[bug - serverOnly - node + typescript] gulp run issue

### ISSUE THREAD

**Issue by AliMD** [ericmdantas/generator-ng-fullstack#137]
I have gulp error after `yo ng-fullstack` with server only and node and typescript

```bash
[18:34:33] Failed to load external module babel-register
[18:34:33] Failed to load external module babel-core/register
[18:34:33] Failed to load external module babel/register
/Volumes/Repositories/starter/ng-fullstack/tasks/default.js:1
(function (exports, require, module, __filename, __dirname) { import gulp from 'gulp';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at requireDir (/Volumes/Repositories/starter/ng-fullstack/node_modules/require-dir/index.js:116:33)
    at Object.<anonymous> (/Volumes/Repositories/starter/ng-fullstack/gulpfile.babel.js:1:85)
```

after `npm i babel-register` i have another error

```bashe
(node:12235) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
module.js:440
    throw err;
    ^

Error: Cannot find module './client/const'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (default.js:2:1)
    at Module._compile (module.js:541:32)
    at loader (/Volumes/Repositories/starter/ng-fullstack/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Volumes/Repositories/starter/ng-fullstack/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
```

**Comment by ericmdantas** [comment]
Hello, @AliMD.

You've got to have `babel`, `babel-cli`, `babel-core` and `babel-preset-es2015` to get that running. All of them being `6.x` and later.

Did the generator finished installing the dependencies?

**Comment by AliMD** [comment]
> Did the generator finished installing the dependencies?

Yes of course

**Comment by ericmdantas** [comment]
Alright, let me reproduce it.

**Comment by ericmdantas** [comment]
The problem is in both `tasks/default.js` and `tasks/index.js`. There should be no

```js
// tasks/default.js

import {tasks} from './client/const';

gulp.task('default', [tasks.CLIENT_WATCH]);
```

since there's no client. Also, there should be no

```js
// tasks/index.js

require('require-dir')('client');
```

in `tasks/index.js`, since, again, there's no client.

After removing those lines, I was able to run `gulp server.compile_tsc`, for example.

**Comment by ericmdantas** [comment]
Also, keep in mind that there's no `gulp` (default task) to run the server when you choose only the server app, you should use `npm start`. 

I'll document it better.

**Comment by ericmdantas** [comment]
`1.7.20` released.

**Comment by AliMD** [comment]
> Also, keep in mind that there's no gulp (default task) to run the server when you choose only the server app, you should use npm start.

Thank you, could you please make a default task and print some tip

**Comment by ericmdantas** [comment]
Sure, will do in `1.8`.
