### ISSUE TITLE
Todo app createTodos and TodoDAO.remove() not working causes test-server to fail.

### ISSUE THREAD

**Issue by comstar** [ericmdantas/generator-ng-fullstack#155]
On a pristine install - Win7, node 4.4.5, npm 2.15.5
Generator Options:
   Type: fullstack
   Server: node 
   Angular: ng1
   Transpiler: node
   http2: no
   Different static server: no

1) TodoDAO.remove() is not removing data from the my-awesome-app_test database.
2) _helpers/db.js createTodos() is not creating the test data in my-awesome-app_test database.

Results from npm run test-server:

```
  Unhandled rejection AssertionError: expected true to be false
    at _onError (todo-dao_test.js:32:17)
    at tryCatcher (C:\workspace\ng-fullstack\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\workspace\ng-fullstack\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (C:\workspace\ng-fullstack\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (C:\workspace\ng-fullstack\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (C:\workspace\ng-fullstack\node_modules\bluebird\js\release\promise.js:679:18)
    at Async._drainQueue (C:\workspace\ng-fullstack\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\workspace\ng-fullstack\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\workspace\ng-fullstack\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)


  4 passing (3s)
  1 failing

  1) todo.dao getAll should get all todos:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at [object Object].<anonymous> (C:\workspace\ng-fullstack\node_modules\mocha\lib\runnable.js:226:19)
```

**Comment by ericmdantas** [comment]
Got to simulate it locally with an empty db.

Working on it.

**Comment by ericmdantas** [comment]
`1.8.7` released.
