### ISSUE TITLE
build-dist error

### ISSUE THREAD

**Issue by uiktiomasfeliz** [ericmdantas/generator-ng-fullstack#156]
i've tried build dist in 3 s.o. same error. Ubuntu, ArchiLinux and windows 10. same issue.

my setup, same build, latest node and npm, the npm run dev works fine, but tests and build-dist just don't works.

This is npm.log

```

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build-dist' ]
2 info using npm@3.9.5
3 info using node@v4.4.5
4 verbose run-script [ 'prebuild-dist', 'build-dist', 'postbuild-dist' ]
5 info lifecycle demo@0.0.1~prebuild-dist: demo@0.0.1
6 silly lifecycle demo@0.0.1~prebuild-dist: no script for prebuild-dist, continuing
7 info lifecycle demo@0.0.1~build-dist: demo@0.0.1
8 verbose lifecycle demo@0.0.1~build-dist: unsafe-perm in lifecycle true
9 verbose lifecycle demo@0.0.1~build-dist: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/acero/Escritorio/Projects/mean/yo-fullstack/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle demo@0.0.1~build-dist: CWD: /home/acero/Escritorio/Projects/mean/yo-fullstack
11 silly lifecycle demo@0.0.1~build-dist: Args: [ '-c', 'gulp client.build:dist' ]
12 silly lifecycle demo@0.0.1~build-dist: Returned: code: 1  signal: null
13 info lifecycle demo@0.0.1~build-dist: Failed to exec build-dist script
14 verbose stack Error: demo@0.0.1 build-dist: `gulp client.build:dist`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid demo@0.0.1
16 verbose cwd /home/acero/Escritorio/Projects/mean/yo-fullstack
17 error Linux 4.4.0-21-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build-dist"
19 error node v4.4.5
20 error npm  v3.9.5
21 error code ELIFECYCLE
22 error demo@0.0.1 build-dist: `gulp client.build:dist`
22 error Exit status 1
23 error Failed at the demo@0.0.1 build-dist script 'gulp client.build:dist'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the demo package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp client.build:dist
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs demo
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls demo
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by ericmdantas** [comment]
Hello, @uiktiomasfeliz.

Could you please post the content of your `.yo-rc.json`?

**Comment by uiktiomasfeliz** [comment]
.yo-rc.json

```

{
  "generator-ng-fullstack": {
    "username": "uiktiomasfeliz",
    "appName": "demo",
    "stack": "fullstack",
    "server": "node",
    "client": "ng2",
    "transpilerServer": "node",
    "secure": false,
    "differentStaticServer": true
  }
}

```

**Comment by ericmdantas** [comment]
Right, I'm pretty sure that's because of https://github.com/ericmdantas/generator-ng-fullstack/issues/101.

Please try the following:
- Go to `tasks/client/build.js`;
- Comment the line `tasks.CLIENT_UNIT_TEST`;
- Run dist again.

Let me know how it goes.

**Comment by uiktiomasfeliz** [comment]
awesome!!! work's like a charm!
Thanks

**Comment by ericmdantas** [comment]
:+1:
