### ISSUE TITLE
Any idea what's wrong with gulp here

### ISSUE THREAD

**Issue by tejasbehra** [ericmdantas/generator-ng-fullstack#209]
/unchanged_yogen/node_ts$ gulp
[15:25:27] Requiring external module babel-register
[15:25:33] Using gulpfile /unchanged_yogen/node_ts/gulpfile.babel.js
[15:25:33] Starting 'client.build_ts'...
[15:25:43] Finished 'client.build_ts' after 9.95 s
[15:25:43] Starting 'client.watch'...
[15:25:43] Finished 'client.watch' after 143 ms
[15:25:43] Starting 'default'...
[15:25:43] Finished 'default' after 64 μs
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3002
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at module.exports.plugin (/mnt/dev/tbehra/clones/unchanged_yogen/node_ts/node_modules/browser-sync/lib/server/index.js:36:25)
    at Object.module.exports.startServer [as fn] (/mnt/dev/tbehra/clones/unchanged_yogen/node_ts/node_modules/browser-sync/lib/async.js:232:52)
    at /mnt/dev/tbehra/clones/unchanged_yogen/node_ts/node_modules/browser-sync/lib/browser-sync.js:149:14
    at iterate (/mnt/dev/tbehra/clones/unchanged_yogen/node_ts/node_modules/browser-sync/lib/utils.js:268:13)
    at /mnt/dev/tbehra/clones/unchanged_yogen/node_ts/node_modules/browser-sync/lib/utils.js:277:25
    at executeTask (/mnt/dev/tbehra/clones/unchanged_yogen/node_ts/node_modules/browser-sync/lib/browser-sync.js:170:13)
    at Object.module.exports.setRewriteRules [as fn] (/mnt/dev/tbehra/clones/unchanged_yogen/node_ts/node_modules/browser-sync/lib/async.js:211:9)
    at /mnt/dev/tbehra/clones/unchanged_yogen/node_ts/node_modules/browser-sync/lib/browser-sync.js:149:14
    at iterate (/mnt/dev/tbehra/clones/unchanged_yogen/node_ts/node_modules/browser-sync/lib/utils.js:268:13)
    at /mnt/dev/tbehra/clones/unchanged_yogen/node_ts/node_modules/browser-sync/lib/utils.js:277:25
    at executeTask (/mnt/dev/tbehra/clones/unchanged_yogen/node_ts/node_modules/browser-sync/lib/browser-sync.js:170:13)

**Comment by ericmdantas** [comment]
`EADDRINUSE :::3002` means that you're already using port `3002` for something else.
