### ISSUE TITLE
npm run dev has error running a hello world project.

### ISSUE THREAD

**Issue by srikanth-chitturi** [ericmdantas/generator-ng-fullstack#235]
> sampleApp@0.0.1 start /home/srikantchitturi/Documents/ng-fullstack
[0] > node index
[0] 
[0] up and running @: SDN-10 on port: 3333
[0] enviroment: undefined
[1] [14:09:49] 
[1] Requiring external module babel-register
[1] [14:10:18] Using gulpfile ~/Documents/ng-fullstack/gulpfile.babel.js
[1] [14:10:19] 
[1] Starting 'client.build_ts'...
[1] [14:10:28] 
[1] Finished 'client.build_ts' after 9.16 s
[1] [14:10:28] Starting 'client.watch'...
[1] [14:10:28] 
[1] 'client.watch' errored after 327 ms
[1] [14:10:28] Error: watch /home/srikantchitturi/Documents/ng-fullstack/client/dev/ ENOSPC
[1]     at exports._errnoException (util.js:893:11)
[1]     at FSWatcher.start (fs.js:1313:19)
[1]     at Object.fs.watch (fs.js:1341:11)
 at Gaze._watchDir (/home/srikantchitturi/Documents/ng-fullstack/node_modules/gaze/lib/gaze.js:289:30)
[1]     at /home/srikantchitturi/Documents/ng-fullstack/node_modules/gaze/lib/gaze.js:358:10
[1]     at iterate (/home/srikantchitturi/Documents/ng-fullstack/node_modules/gaze/lib/helper.js:52:5)
[1]     at Object.forEachSeries (/home/srikantchitturi/Documents/ng-fullstack/node_modules/gaze/lib/helper.js:66:3)
[1]     at Gaze._initWatched (/home/srikantchitturi/Documents/ng-fullstack/node_modules/gaze/lib/gaze.js:354:10)
[1]     at Gaze.add (/home/srikantchitturi/Documents/ng-fullstack/node_modules/gaze/lib/gaze.js:177:8)
[1]     at new Gaze (/home/srikantchitturi/Documents/ng-fullstack/node_modules/gaze/lib/gaze.js:74:10)
[1]     at gaze (/home/srikantchitturi/Documents/ng-fullstack/node_modules/gaze/lib/gaze.js:86:10)
[1]     at Object.module.exports [as watch] (/home/srikantchitturi/Documents/ng-fullstack/node_modules/glob-watcher/index.js:12:17)
[1]     at Gulp.watch (/home/srikantchitturi/Documents/ng-fullstack/node_modules/gulp/index.js:35:16)
[1]     at Gulp.<anonymous> (/home/srikantchitturi/Documents/ng-fullstack/tasks/
client/watch.js:24:15)
[1]     at module.exports (/home/srikantchitturi/Documents/ng-fullstack/node_modules/orchestrator/lib/runTask.js:34:7)
[1]     at Gulp.Orchestrator._runTask (/home/srikantchitturi/Documents/ng-fullstack/node_modules/orchestrator/index.js:273:3)
[1] [BS] Proxying: https://localhost:3333
[1] [BS] Access URLs:
[1]  --------------------------------------
[1]        Local: https://localhost:3000
[1]     External: https://172.10.55.71:3000
[1]  --------------------------------------
[1]           UI: http://localhost:3001
[1]  UI External: http://172.10.55.71:3001
[1]  --------------------------------------

**Comment by ericmdantas** [comment]
Hello, @srikanth-chitturi.

The `ENOSPC` error seems to be a bit weird, here's an issue in `chokidar`'s repo about it: https://github.com/paulmillr/chokidar/issues/294. Unfortunately that's not related to the generator itself, it's more of a gulp and its watcher thing.

See if any of the suggestions there work and let me know how it goes.

**Comment by srikanth-chitturi** [comment]
Ok, Is there any way to run this application now ?

I have run 
npm start

> node index

up and running @: SDN-10 on port: 3333
enviroment: undefined

But even then I cannot open this application .

**Comment by ericmdantas** [comment]
By doing that you're only starting the server, so you'll have to compile the typescript by hand (by running `tsc`).

And then you'll be able to access `localhost:3333`.

**Comment by srikanth-chitturi** [comment]
Yes , I have first run tsc.
Then I run npm start .
Then opened localhost:3333 on the browser.
But even that gives no output in the browser.
My Mongodb instance is also running fine.
Am I missing anything ?

**Comment by ericmdantas** [comment]
Are there any errors in the console? If so, it can be related to #216.

**Comment by srikanth-chitturi** [comment]
There are no errors in console. 

$ npm start

> MyFirstApp@0.0.1 start /home/srikantchitturi/Documents/ng-fullstack-2
> node index

up and running @: SDN-10 on port: 3333
enviroment: undefined

**Comment by ericmdantas** [comment]
@srikanth-chitturi sorry for not being clear; I meant the browser's console.
