### ISSUE TITLE
Error when running test

### ISSUE THREAD

**Issue by ivancalva** [ericmdantas/generator-ng-fullstack#236]
I did a fresh installation of the generator ng2 - node - typescript and im trying to run the tests "npm run test-client" and "npm run test-server" but i get the next error.

**TEST-CLIENT**
`module.js:471
    throw err;
    ^

Error: Cannot find module 'async-each'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ( localpath\node_modules\chokidar\index.js:5:17)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (localpath\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (localpath\node_modules\karma\lib\watcher.js:1:16)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (localpath\node_modules\babel-register\lib\node.js:152:7)`

**TEST-SERVER**
`localpath\node_modules\mocha\lib\utils.js:634
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
        ^

Error: cannot resolve path (or pattern) ''./tests/server/**/*.js''
    at Object.lookupFiles (localpath\node_modules\mocha\lib\utils.js:634:15)
    at localpath\node_modules\mocha\bin\_mocha:327:30
    at Array.forEach (native)
    at Object.<anonymous> (localpath\node_modules\mocha\bin\_mocha:326:6)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3`

is there a confguration im missing to be able to run the tests?

**Comment by ericmdantas** [comment]
Hello, @ivancalva.

Do you have a repo I can take a look? Also, keep in mind the client tests should fail if you're using ng2, see #101. As for the server tests, it should work just fine - do you have `mongod` running?

**Comment by ericmdantas** [comment]
Closing as there was no response.
