### ISSUE TITLE
Error while running 'yo ng-fullstack' with branch v1.9

### ISSUE THREAD

**Issue by rahulswaminathan** [ericmdantas/generator-ng-fullstack#237]
Hi @ericmdantas , I'm getting an error while running `yo ng-fullstack` with the code in branch `v1.9`.

```javascript
$ yo ng-fullstack
D:\GitHub\generator-ng-fullstack\_ng\client\angular.js:6
const {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\GitHub\generator-ng-fullstack\_ng\full\generator.js:7:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

Code in `generator-ng-fullstack\_ng\client\angular.js`:
```javascript
const {
  copyStyleForSubGenerator, 
  copyStyleForMainGenerator,
  normalizeStylePreprocessor
} = require('./style');
```

**Comment by ericmdantas** [comment]
Hello, @rahulswaminathan.

What version of Node you're using? You've got to have version 6+.

**Comment by rahulswaminathan** [comment]
You're right. My node version was 4.x. Upgraded to 6 and it is working now. Thanks!

**Comment by ericmdantas** [comment]
:+1:
