### ISSUE TITLE
go server issues

### ISSUE THREAD

**Issue by pdaniel-frk** [ericmdantas/generator-ng-fullstack#250]
Hello,

I've generated a new project using the provided instructions. Unfortunately i get an error when i try to execute **go get** command : 

go install: no install location for directory .....\server outside GOPATH
        For more details see: go help gopath 

Even if i put server in my gopath, i still get this error. I am using Windows. Also in the docs it is suggested to run **go run main.go** outside server folder. This command also fails with GetFileAttributesEx main.go: The system cannot find the file specified.

Also running **npm run dev** fails with :

[1] [18:51:17]
[1] Requiring external module babel-register
[0]
[0] > raportari@0.0.1 start prj
[0] > node index
[0]
[0] module.js:327
[0]     throw err;
[0]     ^
[0]
[0] Error: Cannot find module '... \index'
[0]     at Function.Module._resolveFilename (module.js:325:15)
[0]     at Function.Module._load (module.js:276:25)
[0]     at Function.Module.runMain (module.js:441:10)
[0]     at startup (node.js:134:18)
[0]     at node.js:962:3
[0]
[0] npm ERR! Windows_NT 10.0.10586
[0] npm ERR! argv "C:\\srv\\nodejs\\node.exe" "... AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
[0] npm ERR! node v4.3.2
[0] npm ERR! npm  v4.1.2
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! raportari@0.0.1 start: `node index`
[0] npm ERR! Exit status 1
[0] npm ERR!
[0] npm ERR! Failed at the raportari@0.0.1 start script 'node index'.
[0] npm ERR! Make sure you have the latest version of node.js and npm installed.
[0] npm ERR! If you do, this is most likely a problem with the raportari package,
[0] npm ERR! not with npm itself.
[0] npm ERR! Tell the author that this fails on your system:
[0] npm ERR!     node index
[0] npm ERR! You can get information on how to open an issue for this project with:
[0] npm ERR!     npm bugs raportari
[0] npm ERR! Or if that isn't available, you can get their info via:
[0] npm ERR!     npm owner ls raportari
[0] npm ERR! There is likely additional logging output above.

Thx

**Comment by ericmdantas** [comment]
Hello, @pdaniel-frk. 

Go server is broken due to some breaking changes made in `echo`'s project (the web framework used) - so it's definetely something I'll have to look into (either update the version or downgrade it). 

Thanks for reporting it.

**Comment by pdaniel-frk** [comment]
I've made some changes for go to compile :

func Init(e *echo.Echo) {
	e.Static("node_modules","node_modules")

	if env := os.Getenv("GO_ENV"); env == "" {
		e.Static("client/dev","client/dev")
	} else {
		e.Static("client/dist","client/dist")
	}
}

But this does not seams to be the problem with the build process. The problems still remains.

**Comment by ericmdantas** [comment]
You mean you can get the server to run, but you can't run `npm run dev`? Can you please try it as `npm run watch`?

**Comment by pdaniel-frk** [comment]
Ok, npm run watch worked. In the UI i see only this message :

{"message":"Not Found"}

Thx

**Comment by ericmdantas** [comment]
The first param for `e.Static` should be a string starting with `/` as in `/myFolder`. Can you please update it an restart the server?

**Comment by pdaniel-frk** [comment]
This is what i did

package static

import (
	"os"

	"github.com/labstack/echo"
)

func Init(e *echo.Echo) {
	e.Static("/node_modules","node_modules")

	if env := os.Getenv("GO_ENV"); env == "" {
		e.Static("/client/dev","client/dev")
	} else {
		e.Static("/client/dist","client/dist")
	}
}

I still get the {"message":"Not Found"} error.

**Comment by pdaniel-frk** [comment]
Ok, after doing this 

func Init(e *echo.Echo) {
	e.Static("/","node_modules")

	if env := os.Getenv("GO_ENV"); env == "" {
		e.Static("/","client/dev")
	} else {
		e.Static("/","client/dist")
	}
}

I managed to get a step forward. Now i see something loading but i get javascript errors

system.js Failed to load resource: the server responded with a status of 404 (Not Found)
Reflect.js Failed to load resource: the server responded with a status of 404 (Not Found)
zone.js Failed to load resource: the server responded with a status of 404 (Not Found)
config.js:1 Uncaught ReferenceError: System is not defined
    at config.js:1
localhost/:27 Uncaught ReferenceError: System is not defined
    at localhost/:27

Probably still something with the paths

**Comment by ericmdantas** [comment]
Now that's an issue with echo, as described here: https://github.com/labstack/echo/issues/838

I'll probably downgrade to `v2` and keep using the former API until it's fixed.

**Comment by ericmdantas** [comment]
Should be fixed in `1.9.3`. 

Please remove the previous echo folder in your `%GOPATH%/src/github/labstack` and run `go get` again.
