### ISSUE TITLE
1.9.0 version error

### ISSUE THREAD

**Issue by pdaniel-frk** [ericmdantas/generator-ng-fullstack#251]
Hello,

I tried using 1.9.0 version on Windows. I get this error when i try to generate the project

.... github\generator-ng-fullstack-1.9.0-0\app\index.js:3
const {Base} = require('yeoman-generator');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.defineProperty.get [as ng-fullstack:app] (C:\Users\\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:40:23)
    at Store.get (C:\Users\\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:64:35)
    at Environment.get (C:\Users\\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:262:16)

I get thi error on **yo ng-fullstack** command

thx

**Comment by ericmdantas** [comment]
Hello, @pdaniel-frk.

You'll need Node 6.x or above to get object destructuring to work.
