### ISSUE TITLE
Problem using this generator

### ISSUE THREAD

**Issue by djcaesar9114** [ericmdantas/generator-ng-fullstack#253]
Hello,
I'm used to coding my own lines, not using anything like Yeoman or other things like this. I read more and more good comments about it, so I tried this ng-fullstack generator. Actually, my experience is so far not as good as I expected.

I explain myself: I tried to generate an app answering the questions this way:

```
? What is the name of your app? testapp
? What is your username? djcaesar9114
? What is your email (used in your package.json)? cesar@djcaesar9114.com
? Which stack do you want? fullstack
? Which Git repository hosting service are you using? github
? Which framework do you want to use in the client side? aurelia1
? Which CSS pre-processor do you want to use? sass
? What language do you want in the server side? node
? Which framework do you want to use in server side? express
? Which transpiler do you want to use in server side? node
? Is it going to be a secure app (HTTP/2)? Yes
? Do you want to keep tests in a different folder? No
? Do you want to use a different static server? Such as NGINX, Apache, IIS, etc? 
(y/N) N
```

Everything went fine, excepted this warning at the end:

└── UNMET PEER DEPENDENCY typescript@~2.0.3 || >=2.0.0-dev || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN gulp-typescript@3.1.5 requires a peer of typescript@~2.0.3 || >=2.0.0-dev || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev but none was installed.
```

I've already something running to the port 3000, so I'd like to change.
I found that the port is configured in `.alivrc`, so I changed it to 3014.
I run `npm run dev` but I see a blank page.
When I press F12, I see that the browser (Firefox or Chrome) doesn't understand why system.js is HTML code:

```
SyntaxError: expected expression, got '<'[En savoir plus]  system.js:1
ReferenceError: System is not defined[En savoir plus]  jspm.config.js:1:1
ReferenceError: System is not defined[En savoir plus]  127.0.0.1:3014:18:7
aliv and kicking!  127.0.0.1:3014:25:15
```

I suppose that it comes from the fact that I chose a wrong transpiler, so I erase everything and answer the questions differently:

```
? What is the name of your app? testapp
? What is your username? djcaesar9114
? What is your email (used in your package.json)? cesar@djcaesar9114.com
? Which stack do you want? fullstack
? Which Git repository hosting service are you using? github
? Which framework do you want to use in the client side? aurelia1
? Which CSS pre-processor do you want to use? sass
? What language do you want in the server side? node
? Which framework do you want to use in server side? express
? Which transpiler do you want to use in server side? typescript
? Is it going to be a secure app (HTTP/2)? No
? Do you want to keep tests in a different folder? No
? Do you want to use a different static server? Such as NGINX, Apache, IIS, etc? 
(y/N) N
```

This time, the app doesn't generate at all, and I see this message in the console:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: /usr/local/lib/node_modules/generator-ng-fullstack/app/templates/server/node/express/server_node_express/config/db.conf.test.ts doesn't exist
    at EditionInterface.module.exports [as read] (/usr/local/lib/node_modules/generator-ng-fullstack/node_modules/mem-fs-editor/actions/read.js:13:3)
    at NgFullstack.template (/usr/local/lib/node_modules/generator-ng-fullstack/node_modules/yeoman-generator/lib/actions/actions.js:198:34)
    at paths.forEach (/usr/local/lib/node_modules/generator-ng-fullstack/_ng/utils/yeoman-utils.js:21:9)
    at Array.forEach (native)
    at Object.exports.directory (/usr/local/lib/node_modules/generator-ng-fullstack/_ng/utils/yeoman-utils.js:20:9)
    at NodeExpressTypescript.copyForMainGenerator (/usr/local/lib/node_modules/generator-ng-fullstack/_ng/server/node_base.js:398:15)
    at MainGenerator.writing (/usr/local/lib/node_modules/generator-ng-fullstack/_ng/full/generator.js:120:53)
    at NgFullstack.writing (/usr/local/lib/node_modules/generator-ng-fullstack/app/index.js:22:22)
    at /usr/local/lib/node_modules/generator-ng-fullstack/node_modules/yeoman-generator/lib/base.js:421:16
    at runCallback (timers.js:651:20)
```

But I never lose my patience, so I decide courageously to change my answers to the questions, like this, after having cleaned my directory:

```
? What is the name of your app? testapp
? What is your username? djcaesar9114
? What is your email (used in your package.json)? cesar@djcaesar9114.com
? Which stack do you want? fullstack
? Which Git repository hosting service are you using? github
? Which framework do you want to use in the client side? aurelia1
? Which CSS pre-processor do you want to use? sass
? What language do you want in the server side? node
? Which framework do you want to use in server side? express
? Which transpiler do you want to use in server side? typescript
? Is it going to be a secure app (HTTP/2)? Yes
? Do you want to keep tests in a different folder? No
? Do you want to use a different static server? Such as NGINX, Apache, IIS, etc? 
(y/N) N
```

And... I got the same error than with the previous answers.

So far, I've spent more time trying to use "generators" than to really create an app, writing it properly with my own code.

Is my problem concerning this particular generator? If that's the case, I would be happy if somebody could give me a hand, because I may be in front of a wonderful world with a key, simply I don't know how to use it. I bet you share my mental suffering.

**Comment by ericmdantas** [comment]
Hey there, @djcaesar9114. Thanks for trying out `ng-fullstack`.

And, yeah, while it can be painful to understand the "black box" that goes in the first generated project, once you do, it's a beautiful world.

But, your problem seems to be related with Aurelia itself (ng1, ng2 and vue2 are working with your options). So it's a bug on our end, I'll label it as such and see what's going on.

Thanks for reporting the issue.

**Comment by djcaesar9114** [comment]
Thanks for you answer. I'll wait until you fix this bug with Aurelia as I really prefer it rather than Angular.

**Comment by ericmdantas** [comment]
Thanks for understanding.

Meanwhile, let me know if you got it working so I can fix it here.

**Comment by ericmdantas** [comment]
Since there's not much support for Aurelia anywhere, I might have to close this one for now.

Might reopen it in the future, if we decide it belong in the `v2`.
