### ISSUE TITLE
generator doesn't work

### ISSUE THREAD

**Issue by Mohsen-Malekan** [ericmdantas/generator-ng-fullstack#255]
`yo ng-fullstack` throws an error
```
D:\Project\ng-fullstack>yo ng-fullstack
C:\Users\Administrator\AppData\Roaming\npm\node_modules\generator-ng-fullstack\app\index.js:3
const {Base} = require('yeoman-generator');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.defineProperty.get [as ng-fullstack:app] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:40:23)
    at Store.get (C:\Users\Administrator\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:64:35)
    at Environment.get (C:\Users\Administrator\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:262:16)
```

**Comment by JankoLancer** [comment]
Same here.

**Comment by JankoLancer** [comment]
Update node to 6.1 and resolve problem.

**Comment by ericmdantas** [comment]
Yup, please update Node to the latest.
