### ISSUE TITLE
Can not create server-side endpoint

### ISSUE THREAD

**Issue by ddesna** [ericmdantas/generator-ng-fullstack#256]
I have this error when I trying to create new NodeJS server-side endpoint:

```
$ yo ng-fullstack:endpoint commons --feature common
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'copyFiles' of undefined
    at EndpointSubGenerator.writing (/usr/local/lib/node_modules/generator-ng-fullstack/_ng/server/sub_generators_endpoint.js:42:74)
    at EndpointGenerator.writing (/usr/local/lib/node_modules/generator-ng-fullstack/endpoint/index.js:18:20)
    at /usr/local/lib/node_modules/generator-ng-fullstack/node_modules/yeoman-generator/lib/base.js:421:16
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

Note: client-side Angular components creates without issues.
Using `generator-ng-fullstack@1.9.5 `

**Comment by ericmdantas** [comment]
Hello, @ddesna.

Can you share the content of you `.yo-rc.json`?

**Comment by ddesna** [comment]
Hi @ericmdantas,

```
{
  "generator-ng-fullstack": {
    "username": "ddesna",
    "appName": "myApp",
    "stack": "fullstack",
    "server": "node",
    "client": "ng2",
    "transpilerServer": "node",
    "secure": true,
    "differentStaticServer": false
  }
}
```

**Comment by ericmdantas** [comment]
I see.

Can you please add the following line there? 

```
{
// ...
"nodeWebFramework": "express"
// ...
}
``` 

And try again? Since there's the options to work with koa now, that's something that's needed in the `yo-rc` file. 

Either way, I'm patching a fix to consider express as the default one. Thanks for the report.

**Comment by ericmdantas** [comment]
`v1.9.6` published with the fix.

**Comment by ddesna** [comment]
Thanks @ericmdantas,
Adding `"nodeWebFramework": "express"` line, it was still happening but after update to `v1.9.6` it's working perfectly.

**Comment by ericmdantas** [comment]
👍
