### ISSUE TITLE
Error running project

### ISSUE THREAD

**Issue by dgleba** [ericmdantas/generator-ng-fullstack#297]
I ran the generator and I get an error starting the app.

Can someone look at my output below and suggest a way I might get it running?

```
? What is your app name? ngf-k7017
? What is your username? dg
? What is your email (used in your package.json)? dgleba@gmail.com
? Which stack do you want? fullstack
? Which Git repository hosting service are you using? github
? Vue2 or Angular1 on client side? vue2
? Which client bundler do you want do use? webpack
? Which CSS pre-processor do you want to use? none
? Node or Go on server side? node
? Express or Koa on the server? express
? Which transpiler do you want to use on the server side? node
? Is it a secure app (HTTP/2)? No
? Do you want to keep tests in separated folders? Yes
? Do you want to use a different static server? Such as NGINX, Apache, IIS, etc? No
? Do you want the TODO boilerplate? Yes
   create package.json
   create README.md
  ...

albe@ubu398j:/srv/file/test/vc/ngf-k7017$ npm run dev

> ngf-k7017@0.0.1 dev /srv/file/test/vc/ngf-k7017
> concurrently "nodemon ./server/index --watch server" "npm run start-client"

 Error occured when executing command: nodemon ./server/index --watch server
 Error: spawn nodemon ENOENT
     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
     at onErrorNT (internal/child_process.js:415:16)
     at process._tickCallback (internal/process/next_tick.js:63:19)
     at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
     at startup (internal/bootstrap/node.js:283:19)
     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
[0] nodemon ./server/index --watch server exited with code -2
[1]
[1] > ngf-k7017@0.0.1 start-client /srv/file/test/vc/ngf-k7017
[1] > webpack-dev-server --progress --config webpack.config.dev.js --content-base client/dev/
[1]
[1] /srv/file/test/vc/ngf-k7017/node_modules/webpack-cli/bin/config-yargs.js:89
[1]                             describe: optionsSchema.definitions.output.properties.path.description,
[1]                                                                        ^
[1]
[1] TypeError: Cannot read property 'properties' of undefined
[1]     at module.exports (/srv/file/test/vc/ngf-k7017/node_modules/webpack-cli/bin/config-yargs.js:89:48)
[1]     at Object.<anonymous> (/srv/file/test/vc/ngf-k7017/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:25)
[1]     at Module._compile (internal/modules/cjs/loader.js:778:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[1]     at Module.load (internal/modules/cjs/loader.js:653:32)
[1]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[1]     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
[1]     at startup (internal/bootstrap/node.js:283:19)
[1]     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
[1] npm
[1]
[1] ERR!
[1]
[1] code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! ngf-k7017@0.0.1 start-client: `webpack-dev-server --progress --config webpack.config.dev.js --content-base client/dev/`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the ngf-k7017@0.0.1 start-client script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm
[1]
[1] ERR!
[1]  A complete log of this run can be found in:
[1] npm
[1]
[1] ERR!
[1]      /home/albe/.npm/_logs/2019-11-05T00_26_07_026Z-debug.log
[1] npm run start-client exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngf-k7017@0.0.1 dev: `concurrently "nodemon ./server/index --watch server" "npm run start-client"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ngf-k7017@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/albe/.npm/_logs/2019-11-05T00_26_07_115Z-debug.log
albe@ubu398j:/srv/file/test/vc/ngf-k7017$

```

**Comment by ericmdantas** [comment]
Hello, @dgleba! 

Which Nodejs version are you using?

**Comment by dgleba** [comment]
```
Running on ubuntu 16.04
albe@ubu398j:~$ node -v
v10.17.0
albe@ubu398j:~$ uname -a
Linux ubu398j.local 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
albe@ubu398j:~$ yarn -v
1.19.1
```

**Comment by ericmdantas** [comment]
Thanks!

Looks like it's an error with the `webpack-cli` lib, can you please update it to `webpack-cli@3.1.1` and try again?

**Comment by dgleba** [comment]
That fixed it. 
thanks.
