### ISSUE TITLE
SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by eikooc** [ericmdantas/generator-ng-fullstack#35]
Ran:
``yo ng-fullstack``

And got the result below. Same error happened when run with sudo

```bash
/usr/lib/node_modules/generator-ng-fullstack/app/index.js:3
const yeoman = require('yeoman-generator');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.defineProperty.get [as ng-fullstack:app] (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:228:16)
```

**Comment by ericmdantas** [comment]
Hello, @eikooc.

You'll need io.js installed to run this generator.

**Comment by trainerbill** [comment]
I get the same error and have iojs installed:

sudo npm install -g iojs
iojs@1.0.0 /usr/local/lib/node_modules/iojs

**Comment by trainerbill** [comment]
Obviously I am late to the iojs party... Didn't know what it was.  I think you should put in the README that iojs is required and link to NVM

https://github.com/creationix/nvm

Makes it easy to install iojs and switch between node and iojs

**Comment by ericmdantas** [comment]
Will do.
