### ISSUE TITLE
Syntax error fails install

### ISSUE THREAD

**Issue by tristanisfeld** [ericmdantas/generator-ng-fullstack#41]
$ yo ng-fullstack
C:\Users\trist\AppData\Roaming\npm\node_modules\generator-ng-fullstack\app\index.js:3
const yeoman = require('yeoman-generator');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.defineProperty.get [as ng-fullstack:app] (c:\Users\trist\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:40:23)
    at Store.get (c:\Users\trist\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:64:35)
    at Environment.get (c:\Users\trist\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:228:16)

**Comment by ericmdantas** [comment]
Hello. This is because you need io.js installed instead of node. Im reverting it, since they're merging io with node =]

**Comment by tristanisfeld** [comment]
Yes, thank you @ericmdantas . I realized that and then closed the issue. I had to uninstall iojs since it broke many packages, but using windows, there is no switcher. So I'm glad you are reverting it :)
