### ISSUE TITLE
Gulp failing from Orchestrator?

### ISSUE THREAD

**Issue by georgeedwards** [ericmdantas/generator-ng-fullstack#90]
Has anyone run into this? I am on windows, just run a clean generation with ng2 and Typescript and my getting started steps aren't working :(. If nobody has seen this, I'll try to fix it in the morning. 

```
[C:\Users\George\Source\Repos\Gen-App>gulp
[23:38:32] Requiring external module babel-register
C:\Users\George\Source\Repos\Gen-App\node_modules\orchestrator\index.js:37
                        throw new Error('Task requires a name');
                        ^

Error: Task requires a name
    at Gulp.Orchestrator.add (C:\Users\George\Source\Repos\Gen-App\node_modules\orchestrator\index.js:37:10)
    at Object.<anonymous> (build_html.js:7:6)
    at Module._compile (module.js:413:34)
    at loader (C:\Users\George\Source\Repos\Gen-App\node_modules\babel-register\lib\node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\George\Source\Repos\Gen-App\node_modules\babel-register\lib\node.js:136:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at requireDir (C:\Users\George\Source\Repos\Gen-App\node_modules\require-dir\index.js:116:33)](url)
```

**Comment by ericmdantas** [comment]
What's the gulp version you're using?

**Comment by georgeedwards** [comment]
CLI - 1.2.1
Local - 3.9.1

**Comment by ericmdantas** [comment]
Alright, doesn't seem related to gulp, I might've messed some task namings up.

**Comment by ericmdantas** [comment]
Got the bug, I'm releasing `-17` with the fix.

**Comment by ericmdantas** [comment]
There, `1.6.0-17` released.

Thanks for pointing it out.
